name: SharePoint-2019-2016-2013-with-an-extensive-configuration
version: 1.0
description: Create a SharePoint 2019 / 2016 / 2013 farm with a web application set with Windows and ADFS authentication, and some path based and host-named site collections. It also provisions User Profiles and Apps service applications and installs claims provider LDAPCP.
engine:  
  type: ARM
  entryPoint: SharePoint-SingleFarm-FullConfig.json